services:
  auth:
    image: datn/auth
    container_name: auth
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - AUTH_DB_URL
      - AUTH_DB_USERNAME
      - AUTH_DB_PASSWORD
      - EUREKA_URI
    ports:
      - 8081:8081

  document-service:
    image: datn/document-service
    container_name: document-service
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_URI
      - MONGODB_URI
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_DATABASE
      - MONGODB_HOST
      - MONGODB_PORT
      - MONGODB_AUTH_DATABASE
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8082:8082
  
  api-gateway:
    image: datn/api-gateway
    container_name: api-gateway
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8080:8080
    environment:
      - ALLOWED_ORIGINS
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_URI

  ai-service:
    image: datn/ai-service
    container_name: ai-service
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_URI
      - OPENAI_KEY
      - MODEL_CONFIG_DB_URL
      - MODEL_CONFIG_DB_USERNAME
      - MODEL_CONFIG_DB_PASSWORD
      - GOOGLE_APPLICATION_CREDENTIALS=/root/key.json
      - VERTEX_PROJECT_ID
      - VERTEX_LOCATION
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD
    volumes:
      - ${VERTEX_SERVICE_ACCOUNT_KEY_PATH:-/dev/null}:/root/key.json:ro
    restart: on-failure
    ports:
      - 8083:8083