# syntax=docker/dockerfile:1
FROM eclipse-temurin:21 AS builder
WORKDIR /application

# Copy Gradle wrapper and build files
COPY gradlew gradlew.bat ./
COPY gradle/ gradle/
COPY gradle.properties build.gradle settings.gradle ./
COPY eclipse-formatter.xml ./

# Use cache mount for Gradle cache directory
RUN --mount=type=cache,target=/root/.gradle \
    chmod +x gradlew && \
    ./gradlew --no-daemon dependencies --quiet

# Copy source code
COPY src/ src/

# Build the application
RUN --mount=type=cache,target=/root/.gradle \
    ./gradlew --no-daemon clean build -x test -x spotlessCheck --build-cache --quiet

# Two .jar files are generated by gradle: one for the application and one for the plain jar.
# We will extract the layers from the application jar.
RUN set -eux; \
    BOOT_JAR="$(ls build/libs/*.jar | grep -v -- '-plain\.jar$' | head -n1)"; \
    test -n "$BOOT_JAR"; \
    java -Djarmode=layertools -jar "$BOOT_JAR" extract

FROM eclipse-temurin:21-jre
WORKDIR /application

# Install postgresql-client for database connectivity checks
RUN apt-get update && \
    apt-get install -y --no-install-recommends postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# Create a non-root user for security
RUN groupadd -r appgroup && useradd -r -g appgroup appuser

# Copy extracted layers from builder stage
COPY --from=builder /application/dependencies/ ./
COPY --from=builder /application/spring-boot-loader/ ./
COPY --from=builder /application/snapshot-dependencies/ ./
COPY --from=builder /application/application/ ./

# Copy initialization script
COPY scripts/init-models.sh /application/scripts/init-models.sh
RUN chmod +x /application/scripts/init-models.sh

# Change ownership to the non-root user
RUN chown -R appuser:appgroup /application

# Switch to non-root user
USER appuser

# Expose the port (default Spring Boot port is 8080)
EXPOSE 8080

# Set Spring profile for Docker environment
ENV SPRING_PROFILES_ACTIVE=docker

# Add health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
    CMD curl -f http://localhost:8080/actuator/health || exit 1

# Set JVM options for containerized environment
ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError"

# Run the application
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS org.springframework.boot.loader.launch.JarLauncher"]
