services:
  auth:
    image: datn/auth
    container_name: auth
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - AUTH_DB_URL=${AUTH_DB_URL}
      - AUTH_DB_USERNAME=${AUTH_DB_USERNAME}
      - AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
      - EUREKA_URI=${EUREKA_URI}
    ports:
      - 8081:8081

  presentation:
    image: datn/presentation
    container_name: presentation
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8082:8082
  
  api-gateway:
    image: datn/api-gateway
    container_name: api-gateway
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8080:8080
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_URI=${EUREKA_URI}

  ai-service:
    image: datn/ai-service
    container_name: ai-service
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_URI=${EUREKA_URI}
      - OPENAI_KEY=${OPENAI_KEY}
      - MODEL_CONFIG_DB_URL=${MODEL_CONFIG_DB_URL}
      - MODEL_CONFIG_DB_USERNAME=${MODEL_CONFIG_DB_USERNAME}
      - MODEL_CONFIG_DB_PASSWORD=${MODEL_CONFIG_DB_PASSWORD}
      - GOOGLE_APPLICATION_CREDENTIALS=/root/key.json
      - VERTEX_PROJECT_ID=${VERTEX_PROJECT_ID}
      - VERTEX_LOCATION=${VERTEX_LOCATION}
    volumes:
      - ${VERTEX_SERVICE_ACCOUNT_KEY_PATH}:/root/key.json:ro
    restart: on-failure
    ports:
      - 8083:8083