spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:${CONFIG_SERVER_URL:http://config-server:8888/}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: presentation
              uri: lb://presentations
              predicates:
                - Path=/presentations/**
            - id: auth
              uri: lb://auth
              predicates:
                - Path=/auth/**
            - id: ai-service
              uri: lb://ai-service
              predicates:
                - Path=/api/ai/**
              filters:
                - RewritePath=/api/ai(?<segment>.*), /$\{segment}