spring:
  application:
    name: ai-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

---

spring:
  config:
    activate:
      on-profile: docker
    import: configserver:${CONFIG_SERVER_URL:http://config-server:8888/}

---

server:
  port: 8083
spring:
  ai:
    chat:
      client:
        enabled: false
    openai:
      api-key: ${OPENAI_KEY}
      base-url: ${OPENAI_API_URL}
      chat:
        options:
          model: ${OPENAI_MODEL_NAME}

  datasource:
    url: ${MODEL_CONFIG_DB_URL}
    username: ${MODEL_CONFIG_DB_USERNAME}
    password: ${MODEL_CONFIG_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  models:
    configurations:
      gpt4o:
        model-name: "openai/gpt-4o-mini"
        display-name: "GPT-4 Optimized"
        max-tokens: 4096
        provider: "OpenAI"
      gemini2_0flash:
        model-name: "gemini-2.0-flash"
        display-name: "Gemini 2.0 Flash"
        max-tokens: 8192
        provider: "Google"
      deepseekchatv3:
        model-name: "deepseek/deepseek-chat-v3-0324:free"
        display-name: "Deepseek Chat V3"
        max-tokens: 4096
        provider: "Deepseek"
