spring:
  application:
    name: ai-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${MODEL_CONFIG_DB_URL:jdbc:postgresql://localhost:5432/model_configuration_db}
    username: ${MODEL_CONFIG_DB_USERNAME:postgres}
    password: ${MODEL_CONFIG_DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
---

spring:
  config:
    activate:
      on-profile: docker
    import: configserver:${CONFIG_SERVER_URL:http://config-server:8888/}