spring:
  application:
    name: ai-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  cloud:
    stream:
      default-binder: rabbit
      bindings:
        ai-events-out-0:  
          destination: ai-events-exchange  
          content-type: application/json
          group: ai-events-group
          producer:
            required-groups: ai-events-group

app:
  messaging:
    binding-name: ai-events-out-0

---

spring:
  config:
    activate:
      on-profile: docker
    import: configserver:${CONFIG_SERVER_URL:http://config-server:8888/}