spring:
  application:
    name: presentation-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888/}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
