spring:
  application:
    name: presentation-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    discovery:
      enabled: false

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://${MONGODB_USERNAME:presentation_user}:${MONGODB_PASSWORD:presentation_password}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DATABASE:presentationdb}?authSource=${MONGODB_AUTH_DATABASE:presentationdb}}

server:
  port: ${SERVER_PORT:8082}

logging:
  level:
    com.datn.document: INFO
    org.springframework.data.mongodb: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:${CONFIG_SERVER_URL:http://config-server:8888/}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://presentation_user:presentation_password@mongo:27017/presentationdb?authSource=presentationdb}
---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongouser:mongopassword@localhost:27017/presentationdb?authSource=admin}
