spring:
  application:
    name: document-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${SERVER_PORT:8082}

logging:
  level:
    com.datn.document: INFO
    org.springframework.data.mongodb: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:${CONFIG_SERVER_URL:http://config-server:8888/}

---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongouser:mongopassword@localhost:27018/presentationdb?authSource=admin}
