-- Init Example Prompts
INSERT INTO example_prompts (id, prompt, icon, type, data, language) VALUES

-- Mindmap Examples (VI)
('1', 'Biển báo giao thông cơ bản', 'Shield', 'MINDMAP', '{}'::jsonb, 'vi'),
('2', 'Gia đình của bé', 'Heart', 'MINDMAP', '{}'::jsonb, 'vi'),
('3', 'Vòng đời của cây xanh', 'TreeDeciduous', 'MINDMAP', '{}'::jsonb, 'vi'),
('4', 'Các mùa trong năm', 'Sun', 'MINDMAP', '{}'::jsonb, 'vi'),
('5', 'Lịch sử Việt Nam qua các thời kỳ', 'Map', 'MINDMAP', '{}'::jsonb, 'vi'),
('6', 'Các phương pháp học tập hiệu quả', 'Brain', 'MINDMAP', '{}'::jsonb, 'vi'),
('7', 'Các loại phương tiện giao thông', 'Car', 'MINDMAP', '{}'::jsonb, 'vi'),
('8', 'Ưu và nhược điểm của mạng xã hội', 'Globe', 'MINDMAP', '{}'::jsonb, 'vi'),
('9', 'Hệ cơ quan trong cơ thể người', 'Activity', 'MINDMAP', '{}'::jsonb, 'vi'),
('10', 'Các loài động vật trong rừng', 'PawPrint', 'MINDMAP', '{}'::jsonb, 'vi'),
('11', 'Lợi ích của việc đọc sách', 'BookOpen', 'MINDMAP', '{}'::jsonb, 'vi'),
('12', 'Các ngày lễ lớn ở Việt Nam', 'Calendar', 'MINDMAP', '{}'::jsonb, 'vi'),
('13', 'Nguyên nhân và hậu quả ô nhiễm môi trường', 'Factory', 'MINDMAP', '{}'::jsonb, 'vi'),
('14', 'Sơ đồ tư duy truyện cổ tích Tấm Cám', 'Feather', 'MINDMAP', '{}'::jsonb, 'vi'),
('15', 'Các loại hình nghệ thuật dân gian', 'Music', 'MINDMAP', '{}'::jsonb, 'vi'),
('16', 'Quy tắc an toàn khi ở nhà một mình', 'Home', 'MINDMAP', '{}'::jsonb, 'vi'),
('17', 'Các bộ phận của máy tính', 'Monitor', 'MINDMAP', '{}'::jsonb, 'vi'),
('18', 'Vòng tuần hoàn của nước', 'CloudRain', 'MINDMAP', '{}'::jsonb, 'vi'),
('19', 'Kỹ năng thoát hiểm khi có hỏa hoạn', 'Flame', 'MINDMAP', '{}'::jsonb, 'vi'),
('20', 'Các hành tinh trong hệ mặt trời', 'Rocket', 'MINDMAP', '{}'::jsonb, 'vi'),
('21', 'Cấu trúc của một bài văn nghị luận', 'PenTool', 'MINDMAP', '{}'::jsonb, 'vi'),
('22', 'Các loại hình năng lượng tái tạo', 'Zap', 'MINDMAP', '{}'::jsonb, 'vi'),
('23', 'Lịch sử phát triển của loài người', 'Hourglass', 'MINDMAP', '{}'::jsonb, 'vi'),
('24', 'Quy trình sản xuất lúa gạo', 'Wheat', 'MINDMAP', '{}'::jsonb, 'vi'),
('25', 'Các biện pháp phòng chống dịch bệnh', 'Stethoscope', 'MINDMAP', '{}'::jsonb, 'vi'),
('26', 'Những lợi ích của việc tập thể dục', 'Dumbbell', 'MINDMAP', '{}'::jsonb, 'vi'),
('27', 'Các loại nhạc cụ dân tộc Việt Nam', 'Music', 'MINDMAP', '{}'::jsonb, 'vi'),
('28', 'Tầm quan trọng của việc học ngoại ngữ', 'Languages', 'MINDMAP', '{}'::jsonb, 'vi'),

-- Mindmap Examples (EN)
('29', 'Basic Traffic Signs', 'Shield', 'MINDMAP', '{}'::jsonb, 'en'),
('30', 'My Family Tree', 'Heart', 'MINDMAP', '{}'::jsonb, 'en'),
('31', 'Life Cycle of a Plant', 'TreeDeciduous', 'MINDMAP', '{}'::jsonb, 'en'),
('32', 'Four Seasons of the Year', 'Sun', 'MINDMAP', '{}'::jsonb, 'en'),
('33', 'History of the World Wars', 'Map', 'MINDMAP', '{}'::jsonb, 'en'),
('34', 'Effective Study Methods', 'Brain', 'MINDMAP', '{}'::jsonb, 'en'),
('35', 'Types of Transportation', 'Car', 'MINDMAP', '{}'::jsonb, 'en'),
('36', 'Pros and Cons of Social Media', 'Globe', 'MINDMAP', '{}'::jsonb, 'en'),
('37', 'Human Body Systems', 'Activity', 'MINDMAP', '{}'::jsonb, 'en'),
('38', 'Animals in the Forest', 'PawPrint', 'MINDMAP', '{}'::jsonb, 'en'),
('39', 'Benefits of Reading Books', 'BookOpen', 'MINDMAP', '{}'::jsonb, 'en'),
('40', 'Major Holidays in Vietnam', 'Calendar', 'MINDMAP', '{}'::jsonb, 'en'),
('41', 'Causes and Effects of Pollution', 'Factory', 'MINDMAP', '{}'::jsonb, 'en'),
('42', 'Mindmap of Cinderella Story', 'Feather', 'MINDMAP', '{}'::jsonb, 'en'),
('43', 'Planets in the Solar System', 'Rocket', 'MINDMAP', '{}'::jsonb, 'en'),
('44', 'Structure of an Argumentative Essay', 'PenTool', 'MINDMAP', '{}'::jsonb, 'en'),
('45', 'Types of Renewable Energy', 'Zap', 'MINDMAP', '{}'::jsonb, 'en'),


-- Presentation Examples (VI)
('46', 'Giới thiệu bản thân em', 'User', 'PRESENTATION', '{}'::jsonb, 'vi'),
('47', 'Món ăn yêu thích của bé', 'Utensils', 'PRESENTATION', '{}'::jsonb, 'vi'),
('48', 'Bảo vệ môi trường sống quanh em', 'Leaf', 'PRESENTATION', '{}'::jsonb, 'vi'),
('49', 'An toàn giao thông đường bộ', 'Bus', 'PRESENTATION', '{}'::jsonb, 'vi'),
('50', 'Kỹ năng làm việc nhóm', 'Users', 'PRESENTATION', '{}'::jsonb, 'vi'),
('51', 'Tương lai của công nghệ AI', 'Bot', 'PRESENTATION', '{}'::jsonb, 'vi'),
('52', 'Các ngày lễ trong năm', 'Calendar', 'PRESENTATION', '{}'::jsonb, 'vi'),
('53', 'Lễ hội Tết Trung Thu', 'Moon', 'PRESENTATION', '{}'::jsonb, 'vi'),
('54', 'Tầm quan trọng của việc đọc sách', 'Book', 'PRESENTATION', '{}'::jsonb, 'vi'),
('55', 'Giới thiệu Câu lạc bộ Tiếng Anh', 'Languages', 'PRESENTATION', '{}'::jsonb, 'vi'),
('56', 'Danh lam thắng cảnh nổi tiếng Việt Nam', 'Camera', 'PRESENTATION', '{}'::jsonb, 'vi'),
('57', 'Tác hại của rác thải nhựa', 'Trash2', 'PRESENTATION', '{}'::jsonb, 'vi'),
('58', 'Một ngày của em', 'Clock', 'PRESENTATION', '{}'::jsonb, 'vi'),
('59', 'Lịch sử Đền Hùng', 'Landmark', 'PRESENTATION', '{}'::jsonb, 'vi'),
('60', 'Giới thiệu cuốn sách yêu thích', 'BookOpen', 'PRESENTATION', '{}'::jsonb, 'vi'),
('61', 'Cách phòng chống dịch bệnh', 'Stethoscope', 'PRESENTATION', '{}'::jsonb, 'vi'),
('62', 'Vai trò của Internet trong học tập', 'Wifi', 'PRESENTATION', '{}'::jsonb, 'vi'),
('63', 'Những phát minh vĩ đại của nhân loại', 'Lightbulb', 'PRESENTATION', '{}'::jsonb, 'vi'),
('64', 'Bảo tồn động vật hoang dã', 'PawPrint', 'PRESENTATION', '{}'::jsonb, 'vi'),
('65', 'Giới thiệu về trường học của em', 'School', 'PRESENTATION', '{}'::jsonb, 'vi'),
('66', 'Các biện pháp tiết kiệm điện', 'Zap', 'PRESENTATION', '{}'::jsonb, 'vi'),
('67', 'Sự phát triển của điện thoại di động', 'Smartphone', 'PRESENTATION', '{}'::jsonb, 'vi'),
('68', 'Trình bày về biến đổi khí hậu', 'Thermometer', 'PRESENTATION', '{}'::jsonb, 'vi'),
('69', 'Kỹ năng thuyết trình trước đám đông', 'Mic', 'PRESENTATION', '{}'::jsonb, 'vi'),
('70', 'Câu chuyện về những người thành công', 'Star', 'PRESENTATION', '{}'::jsonb, 'vi'),

-- Presentation Examples (EN)
('71', 'Introduction about Myself', 'User', 'PRESENTATION', '{}'::jsonb, 'en'),
('72', 'My Favorite Food', 'Utensils', 'PRESENTATION', '{}'::jsonb, 'en'),
('73', 'Protecting Our Environment', 'Leaf', 'PRESENTATION', '{}'::jsonb, 'en'),
('74', 'Traffic Safety Rules', 'Bus', 'PRESENTATION', '{}'::jsonb, 'en'),
('75', 'Teamwork Skills', 'Users', 'PRESENTATION', '{}'::jsonb, 'en'),
('76', 'Future of Artificial Intelligence', 'Bot', 'PRESENTATION', '{}'::jsonb, 'en'),
('77', 'Holidays of the Year', 'Calendar', 'PRESENTATION', '{}'::jsonb, 'en'),
('78', 'Mid-Autumn Festival', 'Moon', 'PRESENTATION', '{}'::jsonb, 'en'),
('79', 'Importance of Reading Books', 'Book', 'PRESENTATION', '{}'::jsonb, 'en'),
('80', 'Introducing English Club', 'Languages', 'PRESENTATION', '{}'::jsonb, 'en'),
('81', 'Famous Landscapes in Vietnam', 'Camera', 'PRESENTATION', '{}'::jsonb, 'en'),
('82', 'Harmful Effects of Plastic Waste', 'Trash2', 'PRESENTATION', '{}'::jsonb, 'en'),
('83', 'My Daily Routine', 'Clock', 'PRESENTATION', '{}'::jsonb, 'en'),
('84', 'History of Hung Temple', 'Landmark', 'PRESENTATION', '{}'::jsonb, 'en'),
('85', 'Book Review Presentation', 'BookOpen', 'PRESENTATION', '{}'::jsonb, 'en'),
('86', 'Energy Saving Tips', 'Zap', 'PRESENTATION', '{}'::jsonb, 'en'),
('87', 'Evolution of Mobile Phones', 'Smartphone', 'PRESENTATION', '{}'::jsonb, 'en'),


-- Image Examples (VI)
('88', 'Chú thỏ trắng đang ăn cà rốt', 'Rabbit', 'IMAGE', '{}'::jsonb, 'vi'),
('89', 'Ngôi nhà kẹo ngọt đầy màu sắc', 'Smile', 'IMAGE', '{}'::jsonb, 'vi'),
('90', 'Trường học thân thiện với nhiều cây xanh', 'School', 'IMAGE', '{}'::jsonb, 'vi'),
('91', 'Phi hành gia khám phá vũ trụ', 'Rocket', 'IMAGE', '{}'::jsonb, 'vi'),
('92', 'Phong cảnh làng quê Việt Nam yên bình', 'Mountain', 'IMAGE', '{}'::jsonb, 'vi'),
('93', 'Thành phố tương lai hiện đại', 'Building2', 'IMAGE', '{}'::jsonb, 'vi'),
('94', 'Một chú rồng lửa nhỏ dễ thương', 'Flame', 'IMAGE', '{}'::jsonb, 'vi'),
('95', 'Nàng tiên cá bơi lội dưới đại dương', 'Fish', 'IMAGE', '{}'::jsonb, 'vi'),
('96', 'Lâu đài cổ tích trên mây', 'Cloud', 'IMAGE', '{}'::jsonb, 'vi'),
('97', 'Khu rừng mùa thu lá vàng', 'Trees', 'IMAGE', '{}'::jsonb, 'vi'),
('98', 'Chú mèo máy Doraemon', 'Cat', 'IMAGE', '{}'::jsonb, 'vi'),
('99', 'Cánh đồng lúa chín vàng', 'Wheat', 'IMAGE', '{}'::jsonb, 'vi'),
('100', 'Lớp học vui nhộn với các bạn nhỏ', 'Users', 'IMAGE', '{}'::jsonb, 'vi'),
('101', 'Bữa cơm gia đình ấm cúng', 'Utensils', 'IMAGE', '{}'::jsonb, 'vi'),
('102', 'Siêu anh hùng bảo vệ trái đất', 'Shield', 'IMAGE', '{}'::jsonb, 'vi'),
('103', 'Chú bộ đội hải quân canh gác biển đảo', 'Ship', 'IMAGE', '{}'::jsonb, 'vi'),
('104', 'Một chú gấu trúc đang ăn trúc', 'Leaf', 'IMAGE', '{}'::jsonb, 'vi'),
('105', 'Cầu vồng rực rỡ sau cơn mưa', 'CloudRain', 'IMAGE', '{}'::jsonb, 'vi'),
('106', 'Đoàn tàu hỏa chạy qua núi', 'Train', 'IMAGE', '{}'::jsonb, 'vi'),
('107', 'Khu vui chơi trẻ em đầy sắc màu', 'FerrisWheel', 'IMAGE', '{}'::jsonb, 'vi'),
('108', 'Chợ nổi miền Tây sông nước', 'Anchor', 'IMAGE', '{}'::jsonb, 'vi'),
('109', 'Một chú robot đang tưới cây', 'Bot', 'IMAGE', '{}'::jsonb, 'vi'),
('110', 'Cảnh hoàng hôn trên bãi biển', 'Sunset', 'IMAGE', '{}'::jsonb, 'vi'),
('111', 'Pháo hoa rực rỡ đêm giao thừa', 'Sparkles', 'IMAGE', '{}'::jsonb, 'vi'),
('112', 'Thư viện sách khổng lồ', 'Library', 'IMAGE', '{}'::jsonb, 'vi'),

-- Image Examples (EN)
('113', 'A cute white rabbit eating a carrot', 'Rabbit', 'IMAGE', '{}'::jsonb, 'en'),
('114', 'A colorful candy house', 'Smile', 'IMAGE', '{}'::jsonb, 'en'),
('115', 'A friendly school with many green trees', 'School', 'IMAGE', '{}'::jsonb, 'en'),
('116', 'Astronaut exploring the universe', 'Rocket', 'IMAGE', '{}'::jsonb, 'en'),
('117', 'Peaceful countryside landscape', 'Mountain', 'IMAGE', '{}'::jsonb, 'en'),
('118', 'Modern futuristic city', 'Building2', 'IMAGE', '{}'::jsonb, 'en'),
('119', 'A cute little fire dragon', 'Flame', 'IMAGE', '{}'::jsonb, 'en'),
('120', 'Mermaid swimming in the ocean', 'Fish', 'IMAGE', '{}'::jsonb, 'en'),
('121', 'Fairy castle on the clouds', 'Cloud', 'IMAGE', '{}'::jsonb, 'en'),
('122', 'Autumn forest with yellow leaves', 'Trees', 'IMAGE', '{}'::jsonb, 'en'),
('123', 'Doraemon the robot cat', 'Cat', 'IMAGE', '{}'::jsonb, 'en'),
('124', 'Golden ripe rice field', 'Wheat', 'IMAGE', '{}'::jsonb, 'en'),
('125', 'Funny classroom with happy kids', 'Users', 'IMAGE', '{}'::jsonb, 'en'),
('126', 'Cozy family dinner', 'Utensils', 'IMAGE', '{}'::jsonb, 'en'),
('127', 'Superhero saving the earth', 'Shield', 'IMAGE', '{}'::jsonb, 'en'),
('128', 'Floating market on the river', 'Anchor', 'IMAGE', '{}'::jsonb, 'en'),
('129', 'A robot watering plants', 'Bot', 'IMAGE', '{}'::jsonb, 'en')
ON CONFLICT (id) DO UPDATE SET prompt = EXCLUDED.prompt, icon = EXCLUDED.icon, type = EXCLUDED.type, data = EXCLUDED.data, language = EXCLUDED.language;
