ALTER TABLE presentations
    ADD COLUMN IF NOT EXISTS grade VARCHAR(50),
    ADD COLUMN IF NOT EXISTS subject VARCHAR(100),
    ADD COLUMN IF NOT EXISTS chapter VARCHAR(255);

ALTER TABLE mindmaps
    ADD COLUMN IF NOT EXISTS grade VARCHAR(50),
    ADD COLUMN IF NOT EXISTS subject VARCHAR(100),
    ADD COLUMN IF NOT EXISTS chapter VARCHAR(255);
