package com.datn.datnbe.temp.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * TEMPORARY — Remove this class after database enrichment is complete.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EnrichmentResultDto {

    /** Total questions generated by the AI. */
    private int totalGenerated;

    /** Questions saved (had at least one image successfully generated). */
    private int totalSaved;

    /** Questions discarded (zero images generated or parse/DB error). */
    private int totalDiscarded;

    /** Total option/pair images successfully generated and uploaded. */
    private int totalImagesGenerated;

    /** Total option/pair image generation attempts that failed. */
    private int totalImagesFailed;

    private List<String> savedQuestionIds;
    private List<String> errors;
}
