#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "===== Running Spotless code formatter on all Java files…"

# Remember the current state
git diff --name-only > /tmp/unstaged_changes.txt
git diff --cached --name-only > /tmp/staged_changes.txt

# Run formatter on all Java files in the project using Spotless
mvn -N spotless:apply

echo "File formatter applied to all Java files."